name: Update Availability Site

on:
  # Triggers the workflow on push or pull request events but only for the trunk branch
  push:
    branches: [ trunk ]
  schedule:
    # Runs at 1:30 AM Eastern Time (6:30 UTC during EST, 5:30 UTC during EDT)
    # This is 1.5 hours after the days_down incrementer
    - cron: "30 6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs the site generation script
      - name: Generate availability site
        run: ./create-site.sh
        
      - name: Push updated site
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'Greg Dryke'
            git config --global user.email 'greg.dryke@gmail.com'
            git commit -am "Updating availability of US government"
            git push
          fi
